### ISSUE TITLE
Global variable fix

### ISSUE THREAD

**Issue by psaletan** [bbog/ghost-backup-script#1]
The script worked well for me, after making these changes:

The config file settings for OUTPUT_PATH and MAX_BACKUP_FILES aren't respected.  The backup uses only the defaults.  I needed to create "global" declarations for each in the setGlobalConfigData() function.

I'm running  a mixed Python 2 & 3 environment (Ubuntu 16.04), defaulting to Python 3.  I added "#!/usr/bin/env python2" as first line.  Without it, the script hung with no output.  

Otherwise, terrific app.  The JSON output diff-ed perfectly with the official export admins can create from the web UI.  Thanks, you saved me a lot of time creating a daily backup.

For the documentation, admins might be interested to know of another way to locate the client_secret value.  They can read it from the database (clients table).

**Comment by bbog** [comment]
Hey, thank you for the comment and also for offering a solution! I'm really glad this was useful for someone.

Regarding to the issues you pointed out, I will look into it tonight.

**Comment by bbog** [comment]
Again, thanks for the heads up and the help. I made a fix for the global variables, it was a huge oversight on my part.

For the [shebang line](https://stackoverflow.com/questions/2429511/why-do-people-write-the-usr-bin-env-python-shebang-on-the-first-line-of-a-pyt), I left things as they were since it seemed particular to your case, with both Python 2 and Python 3 installed on the same system. I'm not that experienced with Python to tell if it's better to add it or not.
